package com.uitstalie.neotrition.api.data;

import com.uitstalie.neotrition.api.data.config.NutritionConfigDataListener;
import com.uitstalie.neotrition.api.data.config.NutritionConfigJson;
import com.uitstalie.neotrition.api.data.effect.NutritionEffectDataListener;
import com.uitstalie.neotrition.api.data.effect.NutritionEffectJson;
import com.uitstalie.neotrition.api.data.group.NutritionGroupDataListener;
import com.uitstalie.neotrition.api.data.group.NutritionGroupJson;
import com.uitstalie.neotrition.api.data.item.NutritionItemDataListener;
import com.uitstalie.neotrition.api.data.item.NutritionItemJson;
import com.uitstalie.neotrition.api.data.item.ItemNutritionSource;
import com.uitstalie.neotrition.api.data.item.MergedItemNutritionSource;
import com.uitstalie.neotrition.api.data.item.AutoGeneratedItemNutritionSource;
import com.uitstalie.neotrition.api.data.item.TagItemNutritionSource;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.neoforge.event.AddReloadListenerEvent;

import java.util.List;
import java.util.Map;

/**
 * 营养数据统一访问入口。
 *
 * <p>集中持有 config/group/item/effect 的 reload listener 和 item neotrition source。
 * 同时提供配置项的便捷访问方法（原 NutritionConfigManager 已迁移至此）。</p>
 */
public final class NutritionDataRegistry {

    private static NutritionConfigDataListener configListener;
    private static NutritionGroupDataListener groupListener;
    private static NutritionItemDataListener itemListener;
    private static NutritionEffectDataListener effectListener;
    private static final MergedItemNutritionSource itemNutritionSource = new MergedItemNutritionSource();
    private static final AutoGeneratedItemNutritionSource autoGeneratedItemSource = new AutoGeneratedItemNutritionSource();
    private static final TagItemNutritionSource tagItemSource = new TagItemNutritionSource();

    private NutritionDataRegistry() {}

    public static void initialize() {
        configListener = new NutritionConfigDataListener();
        groupListener = new NutritionGroupDataListener();
        itemListener = new NutritionItemDataListener();
        effectListener = new NutritionEffectDataListener();
        itemNutritionSource.setSources(List.of(itemListener, autoGeneratedItemSource, tagItemSource));
    }

    public static NutritionConfigDataListener configListener() {
        return configListener;
    }

    public static NutritionGroupDataListener groupListener() {
        return groupListener;
    }

    public static NutritionItemDataListener itemListener() {
        return itemListener;
    }

    public static NutritionEffectDataListener effectListener() {
        return effectListener;
    }

    public static NutritionConfigJson config() {
        return configListener != null ? configListener.getConfig() : null;
    }

    // ── 便捷配置访问（原 NutritionConfigManager，已迁移） ──

    public static boolean isChatLogEnabled() {
        NutritionConfigJson c = config();
        return c != null && c.debug && c.enableChatLog;
    }

    /** debug 模式主开关：控制 ChatLog + BFS 追溯记录。 */
    public static boolean isDebugEnabled() {
        NutritionConfigJson c = config();
        return c != null && c.debug;
    }

    public static boolean isFoodRecordEnabled() {
        NutritionConfigJson c = config();
        return c == null || c.enableFoodRecord;
    }

    public static boolean isAlwaysEatEnabled() {
        NutritionConfigJson c = config();
        return c == null || c.enableAlwaysEat;
    }

    public static NutritionConfigJson.Frequency getFrequency() {
        NutritionConfigJson c = config();
        return c != null ? c.frequency : NutritionConfigJson.Frequency.MEDIUM;
    }

    public static List<NutritionGroupJson> groups() {
        return groupListener != null ? groupListener.getNutritionGroups() : List.of();
    }

    public static NutritionItemJson itemConfig(ResourceLocation itemId) {
        return itemNutritionSource.getItemConfig(itemId);
    }

    public static List<NutritionItemJson> items() {
        return itemNutritionSource.getItems();
    }

    public static ItemNutritionSource itemNutritionSource() {
        return itemNutritionSource;
    }

    public static AutoGeneratedItemNutritionSource autoGeneratedItemSource() {
        return autoGeneratedItemSource;
    }

    public static void setItemNutritionSources(List<ItemNutritionSource> sources) {
        itemNutritionSource.setSources(sources);
    }

    public static Map<ResourceLocation, NutritionEffectJson> effectsByLocation() {
        return effectListener != null ? effectListener.getEffectsWithResourceLocation() : Map.of();
    }

    public static List<NutritionEffectJson> effects() {
        return effectListener != null ? effectListener.getEffects() : List.of();
    }

    public static void loadClasspathDefaults() {
        if (configListener != null) {
            configListener.loadDirectly("data/neotrition/config", "config.json");
        }
        if (groupListener != null) {
            for (String group : DataPackJsonLoader.listJsonFiles("data/neotrition/groups")) {
                groupListener.loadDirectly("data/neotrition/groups", group);
            }
        }
        if (itemListener != null) {
            for (String item : DataPackJsonLoader.listJsonFiles("data/neotrition/items")) {
                itemListener.loadDirectly("data/neotrition/items", item);
            }
        }
        if (effectListener != null) {
            for (String effect : DataPackJsonLoader.listJsonFiles("data/neotrition/effects")) {
                effectListener.loadDirectly("data/neotrition/effects", effect);
            }
        }
        // 0.0.3: BFS 在内存中动态生成，不再从目录加载自动推断结果
    }

    public static void addReloadListeners(AddReloadListenerEvent event) {
        event.addListener(configListener);
        event.addListener(groupListener);
        event.addListener(itemListener);
        event.addListener(effectListener);
    }
}
