package com.uitstalie.nutrition.nutrition.api.data.item;

import net.minecraft.resources.Identifier;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * BFS 自动推断的营养组归属缓存（低优先级，manual JSON + data pack tag 优先）。
 *
 * <p>0.0.3 重构：不再存储 per_value，改为存储 item → groups 映射。
 * 消费时与 item tag 查询合并。</p>
 */
public class AutoGeneratedItemNutritionSource implements ItemNutritionSource {

    private final Map<Identifier, NutritionItemJson> items = new LinkedHashMap<>();
    private final Map<Identifier, Set<String>> groups = new HashMap<>();

    @Override
    public NutritionItemJson getItemConfig(Identifier itemId) {
        return itemId == null ? null : items.get(itemId);
    }

    @Override
    public List<NutritionItemJson> getItems() {
        return items.values().stream().toList();
    }

    /**
     * 获取 BFS 推断的 group 归属。
     *
     * @return item 所属的 group 集合，未推断则返回 null
     */
    public Set<String> getGroups(Identifier itemId) {
        return itemId == null ? null : groups.get(itemId);
    }

    public void clear() {
        items.clear();
        groups.clear();
    }

    /** 获取所有 BFS 推断的 item → groups 映射（只读）。 */
    public Map<Identifier, Set<String>> getAllGroups() {
        return java.util.Collections.unmodifiableMap(groups);
    }

    public void put(Identifier itemId, NutritionItemJson itemJson) {
        if (itemId != null && itemJson != null) {
            items.put(itemId, itemJson);
        }
    }

    public void putGroups(Identifier itemId, Set<String> itemGroups) {
        if (itemId != null && itemGroups != null && !itemGroups.isEmpty()) {
            groups.put(itemId, itemGroups);
        }
    }
}
