package com.uitstalie.nutrition.nutrition.service;

import com.uitstalie.nutrition.nutrition.api.data.NutritionDataRegistry;
import com.uitstalie.nutrition.nutrition.api.data.group.NutritionGroupJson;
import com.uitstalie.nutrition.nutrition.api.data.item.NutritionItemJson;
import com.uitstalie.nutrition.nutrition.util.log.Log;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.MinecraftServer;
import net.minecraft.tags.ItemTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.item.crafting.Recipe;
import net.minecraft.world.item.crafting.RecipeHolder;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.Property;

import java.lang.reflect.Method;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * BFS 配方传播：将已知 item 的 nutrition group tag 沿配方链扩散给产物。
 *
 * <p>0.0.3 重构：不再计算 per_value，只传播 group 成员关系。
 * 结果存入 AutoGeneratedItemNutritionSource，消费时合并查询。</p>
 */
public final class NutritionAutoGenerateService {

    private NutritionAutoGenerateService() {}

    /**
     * 如果配置启用了 auto_generate_on_load，则在服务端启动后触发 autogen。
     *
     * <p>结果存储在内存中，不持久化。每次 JVM 重启都重新运行（BFS < 1s，
     * 签名检查无意义），不依赖 world save 中的历史签名。</p>
     */
    public static void autoGenerateIfNeeded(MinecraftServer server) {
        var config = NutritionDataRegistry.config();
        if (config == null || !config.autoGenerateOnLoad) return;

        Log.w("AutoGen", "Starting auto-generate on server start...");
        generate(server);
    }

    public static void generate(MinecraftServer server) {
        if (server == null) return;

        try {
            NutritionDataRegistry.autoGeneratedItemSource().clear();

            // Step 1: 收集已知 group 归属（从 data pack tag + 手动配置）
            Map<String, Set<String>> knownGroups = collectKnownGroups(server.registryAccess());
            Log.w("AutoGen", "Known groups collected for " + knownGroups.size() + " items");

            // Step 2: 建立 ingredient → recipes 反向索引
            Map<ResourceLocation, List<Recipe<?>>> recipesByIngredient = buildIngredientIndex(server);
            Log.w("AutoGen", "Ingredient index: " + recipesByIngredient.size() + " ingredient keys");

            // Step 3: BFS 扩散
            Deque<String> queue = new ArrayDeque<>(knownGroups.keySet());
            Set<String> enqueued = new HashSet<>(knownGroups.keySet());

            Log.w("AutoGen", "Starting BFS propagation from " + queue.size() + " known items");

            int depth = 0;
            int newCount = 0;
            while (!queue.isEmpty() && depth < 50) {
                int levelSize = queue.size();
                for (int i = 0; i < levelSize; i++) {
                    String currentItemStr = queue.poll();
                    ResourceLocation currentItem = ResourceLocation.tryParse(currentItemStr);
                    if (currentItem == null) continue;

                    Set<String> currentGroups = knownGroups.get(currentItemStr);
                    if (currentGroups == null || currentGroups.isEmpty()) continue;

                    List<Recipe<?>> downstreamRecipes = recipesByIngredient.getOrDefault(currentItem, List.of());
                    for (Recipe<?> recipe : downstreamRecipes) {
                        try {
                            ResourceLocation outputId = getOutputItemId(recipe);
                            if (outputId == null) continue;
                            String outputStr = outputId.toString();

                            // 收集配方中所有原料的 group 并集
                            Set<String> newGroups = collectIngredientGroups(recipe, knownGroups);
                            if (newGroups.isEmpty()) continue;

                            // 合并已有
                            Set<String> existing = knownGroups.get(outputStr);
                            if (existing != null) {
                                Set<String> merged = new HashSet<>(existing);
                                boolean changed = merged.addAll(newGroups);
                                if (!changed) continue;
                                newGroups = merged;
                            }

                            knownGroups.put(outputStr, newGroups);
                            if (enqueued.add(outputStr)) {
                                queue.add(outputStr);
                            }

                            // 写入 autogen source
                            NutritionDataRegistry.autoGeneratedItemSource().putGroups(outputId, newGroups);
                            newCount++;
                        } catch (Exception e) {
                            // skip broken recipe
                        }
                    }
                }
                depth++;
            }

            Log.w("AutoGen", "BFS finished: " + newCount + " new items after " + depth + " levels");

            // Step 4: 将 FeastBlock 的 group 传播到其 servingItem（FD 兼容，仅在 FD 加载时启用）
            if (net.neoforged.fml.ModList.get().isLoaded("farmersdelight")) {
                int feastCount = propagateFeastBlockServings(knownGroups);
                if (feastCount > 0) {
                    Log.w("AutoGen", "FeastBlock propagation: " + feastCount + " serving items");
                }
            }

        } catch (Exception e) {
            Log.e("AutoGen", "Fatal error during auto generate: " + e.getMessage());
            e.printStackTrace();
        }
        // 失效物品缓存，下次 sync 时重建
        NutritionSyncService.invalidateItemEntryCache();
    }

    /** 收集已知 group 归属：从 data pack 的 nutrition group tag + 手动 item JSON 配置。 */
    private static Map<String, Set<String>> collectKnownGroups(
            net.minecraft.core.HolderLookup.Provider registryAccess) {
        Map<String, Set<String>> known = new LinkedHashMap<>();

        // 1. 从 group tag 扫描（#nutrition:fruit 等）
        List<NutritionGroupJson> groups = NutritionDataRegistry.groups();
        for (NutritionGroupJson group : groups) {
            TagKey<Item> groupTag = ItemTags.create(
                    ResourceLocation.fromNamespaceAndPath("nutrition", group.groupName));
            for (Item item : BuiltInRegistries.ITEM) {
                if (item.getDefaultInstance().is(groupTag)) {
                    ResourceLocation itemId = BuiltInRegistries.ITEM.getKey(item);
                    if (itemId == null) continue;
                    known.computeIfAbsent(itemId.toString(), k -> new HashSet<>())
                            .add(group.groupName);
                }
            }
        }

        // 2. 从手动 item JSON 配置补充（items/fruit.json 等）
        var itemListener = NutritionDataRegistry.itemListener();
        if (itemListener != null) {
            for (var entry : itemListener.getGroupConfigs().entrySet()) {
                String groupName = entry.getKey();
                NutritionItemJson config = entry.getValue();
                for (NutritionItemJson.ItemEntry itemEntry : config.items) {
                    String itemId = itemEntry.item();
                    known.computeIfAbsent(itemId, k -> new HashSet<>()).add(groupName);
                }
            }
        }

        return known;
    }

    /**
     * BFS 后处理：将 FeastBlock 的 group tag 传播到其 servingItem。
     * 通过反射读取 {@code servings} property 和 {@code getServingItem(BlockState)} 方法，
     * 不依赖 FD 编译期类。适用于 FarmersDelight 等 mod 的 block→piece 食物链。
     *
     * @return 成功传播的 serving item 数量
     */
    private static int propagateFeastBlockServings(Map<String, Set<String>> knownGroups) {
        int count = 0;
        for (var entry : knownGroups.entrySet()) {
            String blockItemId = entry.getKey();
            Set<String> groups = entry.getValue();
            if (groups == null || groups.isEmpty()) continue;

            ResourceLocation blockId = ResourceLocation.tryParse(blockItemId);
            if (blockId == null) continue;
            Item item = BuiltInRegistries.ITEM.get(blockId);
            if (item == null) continue;
            Block block = Block.byItem(item);
            if (block == Blocks.AIR) continue;

            // 检测 "servings" property → FeastBlock
            BlockState defaultState = block.defaultBlockState();
            Property<Integer> servingsProp = null;
            for (Property<?> prop : defaultState.getProperties()) {
                if (prop.getName().equals("servings")) {
                    try { servingsProp = (Property<Integer>) prop; } catch (ClassCastException ignored) {}
                    break;
                }
            }
            if (servingsProp == null) continue;

            // 反射获取 getServingItem() + getMaxServings()
            try {
                Method getServingMethod = block.getClass().getMethod("getServingItem", BlockState.class);
                Method getMaxMethod = block.getClass().getMethod("getMaxServings");
                int maxServings = (int) getMaxMethod.invoke(block);

                for (int s = maxServings; s >= 1; s--) {
                    BlockState state = defaultState.setValue(servingsProp, s);
                    ItemStack servingStack = (ItemStack) getServingMethod.invoke(block, state);
                    Item servingItem = servingStack.getItem();
                    ResourceLocation servingId = BuiltInRegistries.ITEM.getKey(servingItem);
                    if (servingId == null) continue;

                    // 食材有 FoodProperties 才传播（edible 才有营养值意义）
                    if (servingStack.getFoodProperties(null) != null) {
                        NutritionDataRegistry.autoGeneratedItemSource().putGroups(servingId, groups);
                        count++;
                    }
                }
            } catch (Exception e) {
                // 有 servings property 但不是标准 FeastBlock API，静默跳过
            }
        }
        return count;
    }

    /**
     * 建立 output item → recipes 反向索引。
     * 用于 find-seeds 等命令确定哪些物品有配方产出。
     */
    public static Map<ResourceLocation, List<Recipe<?>>> buildRecipeOutputIndex(MinecraftServer server) {
        Map<ResourceLocation, List<Recipe<?>>> index = new LinkedHashMap<>();
        for (RecipeHolder<?> holder : server.getRecipeManager().getRecipes()) {
            try {
                Recipe<?> recipe = holder.value();
                ResourceLocation outputId = getOutputItemId(recipe);
                if (outputId == null) continue;
                index.computeIfAbsent(outputId, k -> new ArrayList<>()).add(recipe);
            } catch (Exception e) {
                // skip broken recipe
            }
        }
        return index;
    }

    /** 建立 ingredient → recipes 反向索引。 */
    private static Map<ResourceLocation, List<Recipe<?>>> buildIngredientIndex(MinecraftServer server) {
        Map<ResourceLocation, List<Recipe<?>>> index = new LinkedHashMap<>();
        int errorCount = 0;
        for (RecipeHolder<?> holder : server.getRecipeManager().getRecipes()) {
            try {
                Recipe<?> recipe = holder.value();
                ResourceLocation outputId = getOutputItemId(recipe);
                if (outputId == null) continue;

                for (Ingredient ingredient : recipe.getIngredients()) {
                    for (ItemStack ingredientStack : ingredient.getItems()) {
                        ResourceLocation ingredientId = BuiltInRegistries.ITEM.getKey(ingredientStack.getItem());
                        if (ingredientId == null) continue;
                        index.computeIfAbsent(ingredientId, k -> new ArrayList<>()).add(recipe);
                    }
                }
            } catch (Exception e) {
                errorCount++;
                if (errorCount <= 3) {
                    Log.w("AutoGen", "Skipping recipe " + holder.id() + ": " + e.getMessage());
                }
            }
        }
        if (errorCount > 0) {
            Log.w("AutoGen", "Skipped " + errorCount + " broken recipes during indexing");
        }
        return index;
    }

    /** 获取配方产出物品 ID（不再检查 FoodProperties）。 */
    private static ResourceLocation getOutputItemId(Recipe<?> recipe) {
        ItemStack output = recipe.getResultItem(null);
        if (output.isEmpty()) return null;
        Item item = output.getItem();
        return BuiltInRegistries.ITEM.getKey(item);
    }

    /** 收集配方中所有原料的 group 并集。 */
    private static Set<String> collectIngredientGroups(
            Recipe<?> recipe, Map<String, Set<String>> knownGroups) {
        Set<String> union = new HashSet<>();
        for (Ingredient ingredient : recipe.getIngredients()) {
            for (ItemStack ingredientStack : ingredient.getItems()) {
                ResourceLocation ingredientId = BuiltInRegistries.ITEM.getKey(ingredientStack.getItem());
                if (ingredientId == null) continue;
                Set<String> groups = knownGroups.get(ingredientId.toString());
                if (groups != null) {
                    union.addAll(groups);
                }
            }
        }
        return union;
    }
}
