package com.uitstalie.nutrition.nutrition.service;

import com.uitstalie.nutrition.nutrition.api.data.NutritionDataRegistry;
import com.uitstalie.nutrition.nutrition.api.data.config.NutritionConfigJson;
import com.uitstalie.nutrition.nutrition.api.data.group.NutritionGroupJson;
import com.uitstalie.nutrition.nutrition.api.data.item.NutritionItemJson;
import com.uitstalie.nutrition.nutrition.capabilities.nutrition.NutritionCapability;
import com.uitstalie.nutrition.nutrition.registry.AttributeTypeRegistry;
import com.uitstalie.nutrition.nutrition.util.data.NutritionDataStorage;
import com.uitstalie.nutrition.nutrition.util.data.ValueFormulaEvaluator;
import com.uitstalie.nutrition.nutrition.util.log.Log;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.item.ItemStack;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/** 食物食用后的营养应用服务。 */
public final class NutritionFoodService {

    private NutritionFoodService() {}

    public static void applyFoodNutrition(ServerPlayer player, ItemStack itemStack, int healing, float saturation) {
        if (player == null || itemStack == null || itemStack.isEmpty()) return;

        ResourceLocation itemId = BuiltInRegistries.ITEM.getKey(itemStack.getItem());
        if (itemId == null) return;
        String itemIdStr = itemId.toString();

        NutritionCapability cap = player.getData(AttributeTypeRegistry.NutritionCapability);
        if (cap == null) return;

        NutritionConfigJson config = NutritionDataRegistry.config();
        String globalFormula = config != null ? config.valueFormula : null;

        // 收集 item 所属的所有 group（item listener 索引 + BFS autogen）
        Set<String> itemGroups = new HashSet<>();
        var listener = NutritionDataRegistry.itemListener();
        if (listener != null) {
            itemGroups.addAll(listener.getGroupsForItem(itemIdStr));
        }
        Set<String> autogenGroups = NutritionDataRegistry.autoGeneratedItemSource().getGroups(itemId);
        if (autogenGroups != null) {
            itemGroups.addAll(autogenGroups);
        }

        if (itemGroups.isEmpty()) return;

        // 构建 groupName → groupConfig 快速查找
        Map<String, NutritionGroupJson> groupConfigMap = new HashMap<>();
        for (NutritionGroupJson g : NutritionDataRegistry.groups()) {
            groupConfigMap.put(g.groupName, g);
        }

        // 公式求值缓存：同一公式字符串只算一次
        Map<String, Integer> formulaCache = new HashMap<>();

        NutritionDataStorage data = cap.getNutritionData();
        int totalAdded = 0;

        for (String groupName : itemGroups) {
            // 确定该 group 的公式
            NutritionGroupJson groupConfig = groupConfigMap.get(groupName);
            String formula;
            if (groupConfig != null && groupConfig.valueFormula != null) {
                formula = groupConfig.valueFormula;
            } else {
                formula = globalFormula;
            }

            // 公式求值（缓存）
            int formulaValue = formulaCache.computeIfAbsent(
                    formula != null ? formula : "",
                    k -> formula != null ? ValueFormulaEvaluator.evaluate(formula, healing, saturation) : 0);

            // 手动值覆盖
            int addValue = formulaValue;
            if (listener != null) {
                Integer manual = listener.getManualValue(itemIdStr, groupName);
                if (manual != null) {
                    addValue = manual;
                }
            }

            totalAdded += data.addNutrition(groupName, addValue);
        }

        if (config != null && config.isFoodRecordEnabled()) {
            cap.getFoodRecord().addRecord(itemIdStr);
        }

        if (totalAdded > 0) {
            Log.d("NutritionFood", "Player " + player.getName().getString()
                    + " ate " + itemIdStr + " → +" + totalAdded + " nutrition (groups=" + itemGroups + ")");
        }
    }
}
