package com.uitstalie.nutrition.nutrition.service;

import com.uitstalie.nutrition.nutrition.api.data.NutritionDataRegistry;
import com.uitstalie.nutrition.nutrition.api.data.config.NutritionConfigJson;
import com.uitstalie.nutrition.nutrition.api.data.group.NutritionGroupJson;
import com.uitstalie.nutrition.nutrition.capabilities.nutrition.NutritionCapability;
import com.uitstalie.nutrition.nutrition.network.data.NutritionDataSyncPacket;
import com.uitstalie.nutrition.nutrition.util.data.NutritionDataStorage;
import com.uitstalie.nutrition.nutrition.util.data.ValueFormulaEvaluator;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.component.DataComponents;
import net.minecraft.resources.Identifier;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/** 服务端向客户端同步营养状态的应用服务。 */
public final class NutritionSyncService {

    private NutritionSyncService() {}

    public static void syncToClient(ServerPlayer player, NutritionCapability cap) {
        NutritionDataStorage data = cap.getNutritionData();
        Map<String, Integer> values = new LinkedHashMap<>();
        for (String name : data.getGroupNames()) {
            values.put(name, data.getNutrition(name));
        }

        List<NutritionDataSyncPacket.GroupEntry> groupEntries = NutritionDataRegistry.groups().stream()
                .map(g -> new NutritionDataSyncPacket.GroupEntry(
                        g.groupName,
                        g.groupIcon,
                        g.guiTextColor.hex(),
                        g.guiPngColor.hex()))
                .toList();

        List<NutritionDataSyncPacket.EffectEntry> effectEntries = cap.getActiveEffects().stream()
                .map(e -> new NutritionDataSyncPacket.EffectEntry(e.effectId(), e.amplifier()))
                .toList();

        List<NutritionDataSyncPacket.AttributeEntry> attributeEntries = cap.getActiveAttributes().stream()
                .map(a -> new NutritionDataSyncPacket.AttributeEntry(a.attributeId(), a.amount(), a.operation()))
                .toList();

        // 收集物品营养绑定：手动配置 + autogen BFS 传播
        List<NutritionDataSyncPacket.ItemEntry> itemEntries = buildItemEntries();

        NutritionDataSyncPacket.sendTo(
                player,
                values,
                effectEntries,
                groupEntries,
                attributeEntries,
                itemEntries
        );
    }

    /** 构建物品 tooltip 用的营养绑定列表，含手动配置和 autogen 结果，value 由公式计算。 */
    private static List<NutritionDataSyncPacket.ItemEntry> buildItemEntries() {
        // itemId → groupName → 合并所有来源
        Map<String, Map<String, Integer>> itemGroupValues = new LinkedHashMap<>();
        NutritionConfigJson config = NutritionDataRegistry.config();
        String globalFormula = config != null ? config.valueFormula : null;

        // 收集 group config map（formula 查询用）
        Map<String, NutritionGroupJson> groupConfigMap = new HashMap<>();
        for (NutritionGroupJson g : NutritionDataRegistry.groups()) {
            groupConfigMap.put(g.groupName, g);
        }

        // 1. 手动配置来源 (item listener)
        var listener = NutritionDataRegistry.itemListener();
        if (listener != null) {
            for (var groupConfig : listener.getGroupConfigs().values()) {
                String groupName = groupConfig.groups;
                for (var itemEntry : groupConfig.items) {
                    String itemIdStr = itemEntry.item();
                    Integer manualVal = itemEntry.value();
                    int val = resolveItemValue(itemIdStr, groupName, groupConfigMap, manualVal, globalFormula);
                    itemGroupValues.computeIfAbsent(itemIdStr, k -> new LinkedHashMap<>())
                            .putIfAbsent(groupName, val);
                }
            }
        }

        // 2. autogen 来源
        var autogen = NutritionDataRegistry.autoGeneratedItemSource();
        for (var entry : autogen.getAllGroups().entrySet()) {
            String itemIdStr = entry.getKey().toString();
            Set<String> groups = entry.getValue();
            for (String groupName : groups) {
                int val = resolveItemValue(itemIdStr, groupName, groupConfigMap, null, globalFormula);
                itemGroupValues.computeIfAbsent(itemIdStr, k -> new LinkedHashMap<>())
                        .putIfAbsent(groupName, val);
            }
        }

        // 转成网络包格式
        List<NutritionDataSyncPacket.ItemEntry> entries = new ArrayList<>();
        for (var e : itemGroupValues.entrySet()) {
            Identifier itemId = Identifier.tryParse(e.getKey());
            if (itemId == null) continue;
            List<NutritionDataSyncPacket.ItemNutritionEntry> nutritions = new ArrayList<>();
            for (var gv : e.getValue().entrySet()) {
                nutritions.add(new NutritionDataSyncPacket.ItemNutritionEntry(gv.getKey(), gv.getValue()));
            }
            entries.add(new NutritionDataSyncPacket.ItemEntry(itemId.toString(), nutritions));
        }
        return entries;
    }

    /** 计算单个物品在指定 group 中的营养值（手动值优先，否则走公式）。
     *  返回 -1 表示该物品不应出现在 tooltip 中（无 FoodProperties 且无手动值）。 */
    private static int resolveItemValue(String itemIdStr, String groupName,
                                         Map<String, NutritionGroupJson> groupConfigMap,
                                         Integer manualVal, String globalFormula) {
        // 手动值优先
        if (manualVal != null) return manualVal;

        // 解析物品 → FoodProperties
        Identifier itemRl = Identifier.tryParse(itemIdStr);
        if (itemRl == null) return -1;
        Item item = BuiltInRegistries.ITEM.getValue(itemRl);
        ItemStack stack = new ItemStack(item);
        FoodProperties food = stack.get(DataComponents.FOOD);

        // 无 FoodProperties 且无手动值的非食物物品，跳过
        if (food == null) return -1;

        int healing = food.nutrition();
        float saturation = food.saturation();

        // 公式选择：group 独立 > 全局
        NutritionGroupJson groupConfig = groupConfigMap.get(groupName);
        String formula = (groupConfig != null && groupConfig.valueFormula != null)
                ? groupConfig.valueFormula : globalFormula;

        return formula != null ? ValueFormulaEvaluator.evaluate(formula, healing, saturation) : 0;
    }
}
